# Generated by Django 3.1.5 on 2021-01-29 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PazarYerleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlçe')),
                ('count', models.SmallIntegerField(verbose_name='Sayı')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Nokta (Geometry)')),
            ],
        ),
    ]
